# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: simulation.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10simulation.proto\x12\nsimulation\"\x1d\n\tPDRequest\x12\x10\n\x08\x61gv_code\x18\x01 \x01(\t\")\n\x07PDReply\x12\x10\n\x08\x61gv_code\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\".\n\x0c\x46rameRequest\x12\x10\n\x08\x61gv_code\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"\x1d\n\nFrameReply\x12\x0f\n\x07message\x18\x01 \x01(\t2\x83\x01\n\x07SIMGRPC\x12\x37\n\x07GetPD48\x12\x15.simulation.PDRequest\x1a\x13.simulation.PDReply\"\x00\x12?\n\tSendFrame\x12\x18.simulation.FrameRequest\x1a\x16.simulation.FrameReply\"\x00\x42\rZ\x0b/simulationb\x06proto3')



_PDREQUEST = DESCRIPTOR.message_types_by_name['PDRequest']
_PDREPLY = DESCRIPTOR.message_types_by_name['PDReply']
_FRAMEREQUEST = DESCRIPTOR.message_types_by_name['FrameRequest']
_FRAMEREPLY = DESCRIPTOR.message_types_by_name['FrameReply']
PDRequest = _reflection.GeneratedProtocolMessageType('PDRequest', (_message.Message,), {
  'DESCRIPTOR' : _PDREQUEST,
  '__module__' : 'simulation_pb2'
  # @@protoc_insertion_point(class_scope:simulation.PDRequest)
  })
_sym_db.RegisterMessage(PDRequest)

PDReply = _reflection.GeneratedProtocolMessageType('PDReply', (_message.Message,), {
  'DESCRIPTOR' : _PDREPLY,
  '__module__' : 'simulation_pb2'
  # @@protoc_insertion_point(class_scope:simulation.PDReply)
  })
_sym_db.RegisterMessage(PDReply)

FrameRequest = _reflection.GeneratedProtocolMessageType('FrameRequest', (_message.Message,), {
  'DESCRIPTOR' : _FRAMEREQUEST,
  '__module__' : 'simulation_pb2'
  # @@protoc_insertion_point(class_scope:simulation.FrameRequest)
  })
_sym_db.RegisterMessage(FrameRequest)

FrameReply = _reflection.GeneratedProtocolMessageType('FrameReply', (_message.Message,), {
  'DESCRIPTOR' : _FRAMEREPLY,
  '__module__' : 'simulation_pb2'
  # @@protoc_insertion_point(class_scope:simulation.FrameReply)
  })
_sym_db.RegisterMessage(FrameReply)

_SIMGRPC = DESCRIPTOR.services_by_name['SIMGRPC']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\013/simulation'
  _PDREQUEST._serialized_start=32
  _PDREQUEST._serialized_end=61
  _PDREPLY._serialized_start=63
  _PDREPLY._serialized_end=104
  _FRAMEREQUEST._serialized_start=106
  _FRAMEREQUEST._serialized_end=152
  _FRAMEREPLY._serialized_start=154
  _FRAMEREPLY._serialized_end=183
  _SIMGRPC._serialized_start=186
  _SIMGRPC._serialized_end=317
# @@protoc_insertion_point(module_scope)
